/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as VRouteImport } from './routes/v'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as VSlugRouteImport } from './routes/v/$slug'
import { Route as AuthAcceptInvitationInvitationIdRouteImport } from './routes/_auth/accept-invitation/$invitationId'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard/analytics'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedDashboardDocumentsIndexRouteImport } from './routes/_authenticated/dashboard/documents/index'
import { Route as AuthenticatedDashboardLinksIndexRouteImport } from './routes/_authenticated/dashboard/links/index'
import { Route as AuthenticatedDashboardLinksLinkIdRouteImport } from './routes/_authenticated/dashboard/links/$linkId'
import { Route as AuthenticatedDashboardVaultsIndexRouteImport } from './routes/_authenticated/dashboard/vaults/index'
import { Route as AuthenticatedDashboardVaultsVaultIdRouteImport } from './routes/_authenticated/dashboard/vaults/$vaultId'
import { Route as ApiDocumentsDocumentIdBytesRouteImport } from './routes/api/documents/$documentId/bytes'
import { Route as AuthenticatedDashboardDocumentsDocumentIdIndexRouteImport } from './routes/_authenticated/dashboard/documents/$documentId/index'
import { Route as AuthenticatedDashboardDocumentsDocumentIdEditRouteImport } from './routes/_authenticated/dashboard/documents/$documentId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const VRoute = VRouteImport.update({
  id: '/v',
  path: '/v',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const VSlugRoute = VSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VRoute,
} as any)
const AuthAcceptInvitationInvitationIdRoute =
  AuthAcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardDocumentsIndexRoute =
  AuthenticatedDashboardDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLinksIndexRoute =
  AuthenticatedDashboardLinksIndexRouteImport.update({
    id: '/links/',
    path: '/links/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLinksLinkIdRoute =
  AuthenticatedDashboardLinksLinkIdRouteImport.update({
    id: '/links/$linkId',
    path: '/links/$linkId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardVaultsIndexRoute =
  AuthenticatedDashboardVaultsIndexRouteImport.update({
    id: '/vaults/',
    path: '/vaults/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardVaultsVaultIdRoute =
  AuthenticatedDashboardVaultsVaultIdRouteImport.update({
    id: '/vaults/$vaultId',
    path: '/vaults/$vaultId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiDocumentsDocumentIdBytesRoute =
  ApiDocumentsDocumentIdBytesRouteImport.update({
    id: '/api/documents/$documentId/bytes',
    path: '/api/documents/$documentId/bytes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardDocumentsDocumentIdIndexRoute =
  AuthenticatedDashboardDocumentsDocumentIdIndexRouteImport.update({
    id: '/documents/$documentId/',
    path: '/documents/$documentId/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDocumentsDocumentIdEditRoute =
  AuthenticatedDashboardDocumentsDocumentIdEditRouteImport.update({
    id: '/documents/$documentId/edit',
    path: '/documents/$documentId/edit',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/v': typeof VRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/v/$slug': typeof VSlugRoute
  '/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/links/$linkId': typeof AuthenticatedDashboardLinksLinkIdRoute
  '/dashboard/vaults/$vaultId': typeof AuthenticatedDashboardVaultsVaultIdRoute
  '/api/documents/$documentId/bytes': typeof ApiDocumentsDocumentIdBytesRoute
  '/dashboard/documents/': typeof AuthenticatedDashboardDocumentsIndexRoute
  '/dashboard/links/': typeof AuthenticatedDashboardLinksIndexRoute
  '/dashboard/vaults/': typeof AuthenticatedDashboardVaultsIndexRoute
  '/dashboard/documents/$documentId/edit': typeof AuthenticatedDashboardDocumentsDocumentIdEditRoute
  '/dashboard/documents/$documentId/': typeof AuthenticatedDashboardDocumentsDocumentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/v': typeof VRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/v/$slug': typeof VSlugRoute
  '/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/links/$linkId': typeof AuthenticatedDashboardLinksLinkIdRoute
  '/dashboard/vaults/$vaultId': typeof AuthenticatedDashboardVaultsVaultIdRoute
  '/api/documents/$documentId/bytes': typeof ApiDocumentsDocumentIdBytesRoute
  '/dashboard/documents': typeof AuthenticatedDashboardDocumentsIndexRoute
  '/dashboard/links': typeof AuthenticatedDashboardLinksIndexRoute
  '/dashboard/vaults': typeof AuthenticatedDashboardVaultsIndexRoute
  '/dashboard/documents/$documentId/edit': typeof AuthenticatedDashboardDocumentsDocumentIdEditRoute
  '/dashboard/documents/$documentId': typeof AuthenticatedDashboardDocumentsDocumentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/v': typeof VRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/v/$slug': typeof VSlugRoute
  '/_auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/dashboard/links/$linkId': typeof AuthenticatedDashboardLinksLinkIdRoute
  '/_authenticated/dashboard/vaults/$vaultId': typeof AuthenticatedDashboardVaultsVaultIdRoute
  '/api/documents/$documentId/bytes': typeof ApiDocumentsDocumentIdBytesRoute
  '/_authenticated/dashboard/documents/': typeof AuthenticatedDashboardDocumentsIndexRoute
  '/_authenticated/dashboard/links/': typeof AuthenticatedDashboardLinksIndexRoute
  '/_authenticated/dashboard/vaults/': typeof AuthenticatedDashboardVaultsIndexRoute
  '/_authenticated/dashboard/documents/$documentId/edit': typeof AuthenticatedDashboardDocumentsDocumentIdEditRoute
  '/_authenticated/dashboard/documents/$documentId/': typeof AuthenticatedDashboardDocumentsDocumentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/v'
    | '/verify-email'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/v/$slug'
    | '/accept-invitation/$invitationId'
    | '/dashboard/analytics'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/dashboard/links/$linkId'
    | '/dashboard/vaults/$vaultId'
    | '/api/documents/$documentId/bytes'
    | '/dashboard/documents/'
    | '/dashboard/links/'
    | '/dashboard/vaults/'
    | '/dashboard/documents/$documentId/edit'
    | '/dashboard/documents/$documentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/v'
    | '/verify-email'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/v/$slug'
    | '/accept-invitation/$invitationId'
    | '/dashboard/analytics'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/dashboard/links/$linkId'
    | '/dashboard/vaults/$vaultId'
    | '/api/documents/$documentId/bytes'
    | '/dashboard/documents'
    | '/dashboard/links'
    | '/dashboard/vaults'
    | '/dashboard/documents/$documentId/edit'
    | '/dashboard/documents/$documentId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/onboarding'
    | '/v'
    | '/verify-email'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_authenticated/dashboard'
    | '/v/$slug'
    | '/_auth/accept-invitation/$invitationId'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/settings'
    | '/api/auth/$'
    | '/_authenticated/dashboard/links/$linkId'
    | '/_authenticated/dashboard/vaults/$vaultId'
    | '/api/documents/$documentId/bytes'
    | '/_authenticated/dashboard/documents/'
    | '/_authenticated/dashboard/links/'
    | '/_authenticated/dashboard/vaults/'
    | '/_authenticated/dashboard/documents/$documentId/edit'
    | '/_authenticated/dashboard/documents/$documentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  VRoute: typeof VRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDocumentsDocumentIdBytesRoute: typeof ApiDocumentsDocumentIdBytesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v': {
      id: '/v'
      path: '/v'
      fullPath: '/v'
      preLoaderRoute: typeof VRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/v/$slug': {
      id: '/v/$slug'
      path: '/$slug'
      fullPath: '/v/$slug'
      preLoaderRoute: typeof VSlugRouteImport
      parentRoute: typeof VRoute
    }
    '/_auth/accept-invitation/$invitationId': {
      id: '/_auth/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AuthAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/documents/': {
      id: '/_authenticated/dashboard/documents/'
      path: '/documents'
      fullPath: '/dashboard/documents/'
      preLoaderRoute: typeof AuthenticatedDashboardDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/links/': {
      id: '/_authenticated/dashboard/links/'
      path: '/links'
      fullPath: '/dashboard/links/'
      preLoaderRoute: typeof AuthenticatedDashboardLinksIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/links/$linkId': {
      id: '/_authenticated/dashboard/links/$linkId'
      path: '/links/$linkId'
      fullPath: '/dashboard/links/$linkId'
      preLoaderRoute: typeof AuthenticatedDashboardLinksLinkIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/vaults/': {
      id: '/_authenticated/dashboard/vaults/'
      path: '/vaults'
      fullPath: '/dashboard/vaults/'
      preLoaderRoute: typeof AuthenticatedDashboardVaultsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/vaults/$vaultId': {
      id: '/_authenticated/dashboard/vaults/$vaultId'
      path: '/vaults/$vaultId'
      fullPath: '/dashboard/vaults/$vaultId'
      preLoaderRoute: typeof AuthenticatedDashboardVaultsVaultIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/documents/$documentId/bytes': {
      id: '/api/documents/$documentId/bytes'
      path: '/api/documents/$documentId/bytes'
      fullPath: '/api/documents/$documentId/bytes'
      preLoaderRoute: typeof ApiDocumentsDocumentIdBytesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/documents/$documentId/': {
      id: '/_authenticated/dashboard/documents/$documentId/'
      path: '/documents/$documentId'
      fullPath: '/dashboard/documents/$documentId/'
      preLoaderRoute: typeof AuthenticatedDashboardDocumentsDocumentIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/documents/$documentId/edit': {
      id: '/_authenticated/dashboard/documents/$documentId/edit'
      path: '/documents/$documentId/edit'
      fullPath: '/dashboard/documents/$documentId/edit'
      preLoaderRoute: typeof AuthenticatedDashboardDocumentsDocumentIdEditRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthAcceptInvitationInvitationIdRoute: typeof AuthAcceptInvitationInvitationIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthAcceptInvitationInvitationIdRoute: AuthAcceptInvitationInvitationIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardLinksLinkIdRoute: typeof AuthenticatedDashboardLinksLinkIdRoute
  AuthenticatedDashboardVaultsVaultIdRoute: typeof AuthenticatedDashboardVaultsVaultIdRoute
  AuthenticatedDashboardDocumentsIndexRoute: typeof AuthenticatedDashboardDocumentsIndexRoute
  AuthenticatedDashboardLinksIndexRoute: typeof AuthenticatedDashboardLinksIndexRoute
  AuthenticatedDashboardVaultsIndexRoute: typeof AuthenticatedDashboardVaultsIndexRoute
  AuthenticatedDashboardDocumentsDocumentIdEditRoute: typeof AuthenticatedDashboardDocumentsDocumentIdEditRoute
  AuthenticatedDashboardDocumentsDocumentIdIndexRoute: typeof AuthenticatedDashboardDocumentsDocumentIdIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardLinksLinkIdRoute:
      AuthenticatedDashboardLinksLinkIdRoute,
    AuthenticatedDashboardVaultsVaultIdRoute:
      AuthenticatedDashboardVaultsVaultIdRoute,
    AuthenticatedDashboardDocumentsIndexRoute:
      AuthenticatedDashboardDocumentsIndexRoute,
    AuthenticatedDashboardLinksIndexRoute:
      AuthenticatedDashboardLinksIndexRoute,
    AuthenticatedDashboardVaultsIndexRoute:
      AuthenticatedDashboardVaultsIndexRoute,
    AuthenticatedDashboardDocumentsDocumentIdEditRoute:
      AuthenticatedDashboardDocumentsDocumentIdEditRoute,
    AuthenticatedDashboardDocumentsDocumentIdIndexRoute:
      AuthenticatedDashboardDocumentsDocumentIdIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface VRouteChildren {
  VSlugRoute: typeof VSlugRoute
}

const VRouteChildren: VRouteChildren = {
  VSlugRoute: VSlugRoute,
}

const VRouteWithChildren = VRoute._addFileChildren(VRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  VRoute: VRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDocumentsDocumentIdBytesRoute: ApiDocumentsDocumentIdBytesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
