/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as VRouteImport } from './routes/v'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthTwoFactorRouteImport } from './routes/_auth/two-factor'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as OperationsEnrollRouteImport } from './routes/operations/enroll'
import { Route as VSlugRouteImport } from './routes/v/$slug'
import { Route as AuthAcceptInvitationInvitationIdRouteImport } from './routes/_auth/accept-invitation/$invitationId'
import { Route as AuthenticatedDashboardDocumentsRouteRouteImport } from './routes/_authenticated/dashboard/documents/route'
import { Route as AuthenticatedDashboardPeopleRouteImport } from './routes/_authenticated/dashboard/people'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDemoEndRouteImport } from './routes/api/demo/end'
import { Route as ApiDemoEntryRouteImport } from './routes/api/demo/entry'
import { Route as ApiOperationsDemoRecordsRouteImport } from './routes/api/operations/demo-records'
import { Route as ApiOperationsPolicyRouteImport } from './routes/api/operations/policy'
import { Route as ApiOperationsReaperRouteImport } from './routes/api/operations/reaper'
import { Route as VSlugIndexRouteImport } from './routes/v/$slug.index'
import { Route as VSlugDocumentIdRouteImport } from './routes/v/$slug.$documentId'
import { Route as VSlugBeaconRouteImport } from './routes/v/$slug.beacon'
import { Route as AuthenticatedDashboardAnalyticsIndexRouteImport } from './routes/_authenticated/dashboard/analytics.index'
import { Route as AuthenticatedDashboardAnalyticsLinkIdRouteImport } from './routes/_authenticated/dashboard/analytics.$linkId'
import { Route as AuthenticatedDashboardDocumentsIndexRouteImport } from './routes/_authenticated/dashboard/documents/index'
import { Route as AuthenticatedDashboardLinksIndexRouteImport } from './routes/_authenticated/dashboard/links/index'
import { Route as AuthenticatedDashboardLinksLinkIdRouteImport } from './routes/_authenticated/dashboard/links/$linkId'
import { Route as AuthenticatedDashboardVaultsIndexRouteImport } from './routes/_authenticated/dashboard/vaults/index'
import { Route as AuthenticatedDashboardVaultsVaultIdRouteImport } from './routes/_authenticated/dashboard/vaults/$vaultId'
import { Route as ApiDemoReportsSlugRouteImport } from './routes/api/demo/reports/$slug'
import { Route as ApiDocumentsDocumentIdBytesRouteImport } from './routes/api/documents/$documentId/bytes'
import { Route as VSlugBytesDocumentIdRouteImport } from './routes/v/$slug.bytes.$documentId'
import { Route as AuthenticatedDashboardDocumentsDocumentIdIndexRouteImport } from './routes/_authenticated/dashboard/documents/$documentId/index'
import { Route as AuthenticatedDashboardDocumentsDocumentIdEditRouteImport } from './routes/_authenticated/dashboard/documents/$documentId/edit'
import { Route as ApiOperationsDemoEnvironmentsEnvironmentIdEndRouteImport } from './routes/api/operations/demo-environments/$environmentId/end'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const VRoute = VRouteImport.update({
  id: '/v',
  path: '/v',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const OperationsEnrollRoute = OperationsEnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => OperationsRoute,
} as any)
const VSlugRoute = VSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VRoute,
} as any)
const AuthAcceptInvitationInvitationIdRoute =
  AuthAcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthenticatedDashboardDocumentsRouteRoute =
  AuthenticatedDashboardDocumentsRouteRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPeopleRoute =
  AuthenticatedDashboardPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoEndRoute = ApiDemoEndRouteImport.update({
  id: '/api/demo/end',
  path: '/api/demo/end',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoEntryRoute = ApiDemoEntryRouteImport.update({
  id: '/api/demo/entry',
  path: '/api/demo/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperationsDemoRecordsRoute =
  ApiOperationsDemoRecordsRouteImport.update({
    id: '/api/operations/demo-records',
    path: '/api/operations/demo-records',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOperationsPolicyRoute = ApiOperationsPolicyRouteImport.update({
  id: '/api/operations/policy',
  path: '/api/operations/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperationsReaperRoute = ApiOperationsReaperRouteImport.update({
  id: '/api/operations/reaper',
  path: '/api/operations/reaper',
  getParentRoute: () => rootRouteImport,
} as any)
const VSlugIndexRoute = VSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VSlugRoute,
} as any)
const VSlugDocumentIdRoute = VSlugDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => VSlugRoute,
} as any)
const VSlugBeaconRoute = VSlugBeaconRouteImport.update({
  id: '/beacon',
  path: '/beacon',
  getParentRoute: () => VSlugRoute,
} as any)
const AuthenticatedDashboardAnalyticsIndexRoute =
  AuthenticatedDashboardAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnalyticsLinkIdRoute =
  AuthenticatedDashboardAnalyticsLinkIdRouteImport.update({
    id: '/analytics/$linkId',
    path: '/analytics/$linkId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDocumentsIndexRoute =
  AuthenticatedDashboardDocumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardDocumentsRouteRoute,
  } as any)
const AuthenticatedDashboardLinksIndexRoute =
  AuthenticatedDashboardLinksIndexRouteImport.update({
    id: '/links/',
    path: '/links/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLinksLinkIdRoute =
  AuthenticatedDashboardLinksLinkIdRouteImport.update({
    id: '/links/$linkId',
    path: '/links/$linkId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardVaultsIndexRoute =
  AuthenticatedDashboardVaultsIndexRouteImport.update({
    id: '/vaults/',
    path: '/vaults/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardVaultsVaultIdRoute =
  AuthenticatedDashboardVaultsVaultIdRouteImport.update({
    id: '/vaults/$vaultId',
    path: '/vaults/$vaultId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiDemoReportsSlugRoute = ApiDemoReportsSlugRouteImport.update({
  id: '/api/demo/reports/$slug',
  path: '/api/demo/reports/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsDocumentIdBytesRoute =
  ApiDocumentsDocumentIdBytesRouteImport.update({
    id: '/api/documents/$documentId/bytes',
    path: '/api/documents/$documentId/bytes',
    getParentRoute: () => rootRouteImport,
  } as any)
const VSlugBytesDocumentIdRoute = VSlugBytesDocumentIdRouteImport.update({
  id: '/bytes/$documentId',
  path: '/bytes/$documentId',
  getParentRoute: () => VSlugRoute,
} as any)
const AuthenticatedDashboardDocumentsDocumentIdIndexRoute =
  AuthenticatedDashboardDocumentsDocumentIdIndexRouteImport.update({
    id: '/$documentId/',
    path: '/$documentId/',
    getParentRoute: () => AuthenticatedDashboardDocumentsRouteRoute,
  } as any)
const AuthenticatedDashboardDocumentsDocumentIdEditRoute =
  AuthenticatedDashboardDocumentsDocumentIdEditRouteImport.update({
    id: '/$documentId/edit',
    path: '/$documentId/edit',
    getParentRoute: () => AuthenticatedDashboardDocumentsRouteRoute,
  } as any)
const ApiOperationsDemoEnvironmentsEnvironmentIdEndRoute =
  ApiOperationsDemoEnvironmentsEnvironmentIdEndRouteImport.update({
    id: '/api/operations/demo-environments/$environmentId/end',
    path: '/api/operations/demo-environments/$environmentId/end',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/operations': typeof OperationsRouteWithChildren
  '/v': typeof VRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/operations/enroll': typeof OperationsEnrollRoute
  '/v/$slug': typeof VSlugRouteWithChildren
  '/dashboard/documents': typeof AuthenticatedDashboardDocumentsRouteRouteWithChildren
  '/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/dashboard/people': typeof AuthenticatedDashboardPeopleRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/end': typeof ApiDemoEndRoute
  '/api/demo/entry': typeof ApiDemoEntryRoute
  '/api/operations/demo-records': typeof ApiOperationsDemoRecordsRoute
  '/api/operations/policy': typeof ApiOperationsPolicyRoute
  '/api/operations/reaper': typeof ApiOperationsReaperRoute
  '/v/$slug/$documentId': typeof VSlugDocumentIdRoute
  '/v/$slug/beacon': typeof VSlugBeaconRoute
  '/v/$slug/': typeof VSlugIndexRoute
  '/dashboard/analytics/$linkId': typeof AuthenticatedDashboardAnalyticsLinkIdRoute
  '/dashboard/links/$linkId': typeof AuthenticatedDashboardLinksLinkIdRoute
  '/dashboard/vaults/$vaultId': typeof AuthenticatedDashboardVaultsVaultIdRoute
  '/api/demo/reports/$slug': typeof ApiDemoReportsSlugRoute
  '/api/documents/$documentId/bytes': typeof ApiDocumentsDocumentIdBytesRoute
  '/v/$slug/bytes/$documentId': typeof VSlugBytesDocumentIdRoute
  '/dashboard/analytics/': typeof AuthenticatedDashboardAnalyticsIndexRoute
  '/dashboard/documents/': typeof AuthenticatedDashboardDocumentsIndexRoute
  '/dashboard/links/': typeof AuthenticatedDashboardLinksIndexRoute
  '/dashboard/vaults/': typeof AuthenticatedDashboardVaultsIndexRoute
  '/dashboard/documents/$documentId/edit': typeof AuthenticatedDashboardDocumentsDocumentIdEditRoute
  '/api/operations/demo-environments/$environmentId/end': typeof ApiOperationsDemoEnvironmentsEnvironmentIdEndRoute
  '/dashboard/documents/$documentId/': typeof AuthenticatedDashboardDocumentsDocumentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/operations': typeof OperationsRouteWithChildren
  '/v': typeof VRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/operations/enroll': typeof OperationsEnrollRoute
  '/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/dashboard/people': typeof AuthenticatedDashboardPeopleRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/end': typeof ApiDemoEndRoute
  '/api/demo/entry': typeof ApiDemoEntryRoute
  '/api/operations/demo-records': typeof ApiOperationsDemoRecordsRoute
  '/api/operations/policy': typeof ApiOperationsPolicyRoute
  '/api/operations/reaper': typeof ApiOperationsReaperRoute
  '/v/$slug/$documentId': typeof VSlugDocumentIdRoute
  '/v/$slug/beacon': typeof VSlugBeaconRoute
  '/v/$slug': typeof VSlugIndexRoute
  '/dashboard/analytics/$linkId': typeof AuthenticatedDashboardAnalyticsLinkIdRoute
  '/dashboard/links/$linkId': typeof AuthenticatedDashboardLinksLinkIdRoute
  '/dashboard/vaults/$vaultId': typeof AuthenticatedDashboardVaultsVaultIdRoute
  '/api/demo/reports/$slug': typeof ApiDemoReportsSlugRoute
  '/api/documents/$documentId/bytes': typeof ApiDocumentsDocumentIdBytesRoute
  '/v/$slug/bytes/$documentId': typeof VSlugBytesDocumentIdRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsIndexRoute
  '/dashboard/documents': typeof AuthenticatedDashboardDocumentsIndexRoute
  '/dashboard/links': typeof AuthenticatedDashboardLinksIndexRoute
  '/dashboard/vaults': typeof AuthenticatedDashboardVaultsIndexRoute
  '/dashboard/documents/$documentId/edit': typeof AuthenticatedDashboardDocumentsDocumentIdEditRoute
  '/api/operations/demo-environments/$environmentId/end': typeof ApiOperationsDemoEnvironmentsEnvironmentIdEndRoute
  '/dashboard/documents/$documentId': typeof AuthenticatedDashboardDocumentsDocumentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/operations': typeof OperationsRouteWithChildren
  '/v': typeof VRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/two-factor': typeof AuthTwoFactorRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/operations/enroll': typeof OperationsEnrollRoute
  '/v/$slug': typeof VSlugRouteWithChildren
  '/_authenticated/dashboard/documents': typeof AuthenticatedDashboardDocumentsRouteRouteWithChildren
  '/_auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/_authenticated/dashboard/people': typeof AuthenticatedDashboardPeopleRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/end': typeof ApiDemoEndRoute
  '/api/demo/entry': typeof ApiDemoEntryRoute
  '/api/operations/demo-records': typeof ApiOperationsDemoRecordsRoute
  '/api/operations/policy': typeof ApiOperationsPolicyRoute
  '/api/operations/reaper': typeof ApiOperationsReaperRoute
  '/v/$slug/$documentId': typeof VSlugDocumentIdRoute
  '/v/$slug/beacon': typeof VSlugBeaconRoute
  '/v/$slug/': typeof VSlugIndexRoute
  '/_authenticated/dashboard/analytics/$linkId': typeof AuthenticatedDashboardAnalyticsLinkIdRoute
  '/_authenticated/dashboard/links/$linkId': typeof AuthenticatedDashboardLinksLinkIdRoute
  '/_authenticated/dashboard/vaults/$vaultId': typeof AuthenticatedDashboardVaultsVaultIdRoute
  '/api/demo/reports/$slug': typeof ApiDemoReportsSlugRoute
  '/api/documents/$documentId/bytes': typeof ApiDocumentsDocumentIdBytesRoute
  '/v/$slug/bytes/$documentId': typeof VSlugBytesDocumentIdRoute
  '/_authenticated/dashboard/analytics/': typeof AuthenticatedDashboardAnalyticsIndexRoute
  '/_authenticated/dashboard/documents/': typeof AuthenticatedDashboardDocumentsIndexRoute
  '/_authenticated/dashboard/links/': typeof AuthenticatedDashboardLinksIndexRoute
  '/_authenticated/dashboard/vaults/': typeof AuthenticatedDashboardVaultsIndexRoute
  '/_authenticated/dashboard/documents/$documentId/edit': typeof AuthenticatedDashboardDocumentsDocumentIdEditRoute
  '/api/operations/demo-environments/$environmentId/end': typeof ApiOperationsDemoEnvironmentsEnvironmentIdEndRoute
  '/_authenticated/dashboard/documents/$documentId/': typeof AuthenticatedDashboardDocumentsDocumentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/operations'
    | '/v'
    | '/verify-email'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/two-factor'
    | '/dashboard'
    | '/operations/enroll'
    | '/v/$slug'
    | '/dashboard/documents'
    | '/accept-invitation/$invitationId'
    | '/dashboard/people'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/api/demo/end'
    | '/api/demo/entry'
    | '/api/operations/demo-records'
    | '/api/operations/policy'
    | '/api/operations/reaper'
    | '/v/$slug/$documentId'
    | '/v/$slug/beacon'
    | '/v/$slug/'
    | '/dashboard/analytics/$linkId'
    | '/dashboard/links/$linkId'
    | '/dashboard/vaults/$vaultId'
    | '/api/demo/reports/$slug'
    | '/api/documents/$documentId/bytes'
    | '/v/$slug/bytes/$documentId'
    | '/dashboard/analytics/'
    | '/dashboard/documents/'
    | '/dashboard/links/'
    | '/dashboard/vaults/'
    | '/dashboard/documents/$documentId/edit'
    | '/api/operations/demo-environments/$environmentId/end'
    | '/dashboard/documents/$documentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/operations'
    | '/v'
    | '/verify-email'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/two-factor'
    | '/dashboard'
    | '/operations/enroll'
    | '/accept-invitation/$invitationId'
    | '/dashboard/people'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/api/demo/end'
    | '/api/demo/entry'
    | '/api/operations/demo-records'
    | '/api/operations/policy'
    | '/api/operations/reaper'
    | '/v/$slug/$documentId'
    | '/v/$slug/beacon'
    | '/v/$slug'
    | '/dashboard/analytics/$linkId'
    | '/dashboard/links/$linkId'
    | '/dashboard/vaults/$vaultId'
    | '/api/demo/reports/$slug'
    | '/api/documents/$documentId/bytes'
    | '/v/$slug/bytes/$documentId'
    | '/dashboard/analytics'
    | '/dashboard/documents'
    | '/dashboard/links'
    | '/dashboard/vaults'
    | '/dashboard/documents/$documentId/edit'
    | '/api/operations/demo-environments/$environmentId/end'
    | '/dashboard/documents/$documentId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/onboarding'
    | '/operations'
    | '/v'
    | '/verify-email'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/two-factor'
    | '/_authenticated/dashboard'
    | '/operations/enroll'
    | '/v/$slug'
    | '/_authenticated/dashboard/documents'
    | '/_auth/accept-invitation/$invitationId'
    | '/_authenticated/dashboard/people'
    | '/_authenticated/dashboard/settings'
    | '/api/auth/$'
    | '/api/demo/end'
    | '/api/demo/entry'
    | '/api/operations/demo-records'
    | '/api/operations/policy'
    | '/api/operations/reaper'
    | '/v/$slug/$documentId'
    | '/v/$slug/beacon'
    | '/v/$slug/'
    | '/_authenticated/dashboard/analytics/$linkId'
    | '/_authenticated/dashboard/links/$linkId'
    | '/_authenticated/dashboard/vaults/$vaultId'
    | '/api/demo/reports/$slug'
    | '/api/documents/$documentId/bytes'
    | '/v/$slug/bytes/$documentId'
    | '/_authenticated/dashboard/analytics/'
    | '/_authenticated/dashboard/documents/'
    | '/_authenticated/dashboard/links/'
    | '/_authenticated/dashboard/vaults/'
    | '/_authenticated/dashboard/documents/$documentId/edit'
    | '/api/operations/demo-environments/$environmentId/end'
    | '/_authenticated/dashboard/documents/$documentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  OperationsRoute: typeof OperationsRouteWithChildren
  VRoute: typeof VRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDemoEndRoute: typeof ApiDemoEndRoute
  ApiDemoEntryRoute: typeof ApiDemoEntryRoute
  ApiOperationsDemoRecordsRoute: typeof ApiOperationsDemoRecordsRoute
  ApiOperationsPolicyRoute: typeof ApiOperationsPolicyRoute
  ApiOperationsReaperRoute: typeof ApiOperationsReaperRoute
  ApiDemoReportsSlugRoute: typeof ApiDemoReportsSlugRoute
  ApiDocumentsDocumentIdBytesRoute: typeof ApiDocumentsDocumentIdBytesRoute
  ApiOperationsDemoEnvironmentsEnvironmentIdEndRoute: typeof ApiOperationsDemoEnvironmentsEnvironmentIdEndRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v': {
      id: '/v'
      path: '/v'
      fullPath: '/v'
      preLoaderRoute: typeof VRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/two-factor': {
      id: '/_auth/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/operations/enroll': {
      id: '/operations/enroll'
      path: '/enroll'
      fullPath: '/operations/enroll'
      preLoaderRoute: typeof OperationsEnrollRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/v/$slug': {
      id: '/v/$slug'
      path: '/$slug'
      fullPath: '/v/$slug'
      preLoaderRoute: typeof VSlugRouteImport
      parentRoute: typeof VRoute
    }
    '/_auth/accept-invitation/$invitationId': {
      id: '/_auth/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AuthAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard/documents': {
      id: '/_authenticated/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof AuthenticatedDashboardDocumentsRouteRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/people': {
      id: '/_authenticated/dashboard/people'
      path: '/people'
      fullPath: '/dashboard/people'
      preLoaderRoute: typeof AuthenticatedDashboardPeopleRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/end': {
      id: '/api/demo/end'
      path: '/api/demo/end'
      fullPath: '/api/demo/end'
      preLoaderRoute: typeof ApiDemoEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/entry': {
      id: '/api/demo/entry'
      path: '/api/demo/entry'
      fullPath: '/api/demo/entry'
      preLoaderRoute: typeof ApiDemoEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operations/demo-records': {
      id: '/api/operations/demo-records'
      path: '/api/operations/demo-records'
      fullPath: '/api/operations/demo-records'
      preLoaderRoute: typeof ApiOperationsDemoRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operations/policy': {
      id: '/api/operations/policy'
      path: '/api/operations/policy'
      fullPath: '/api/operations/policy'
      preLoaderRoute: typeof ApiOperationsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operations/reaper': {
      id: '/api/operations/reaper'
      path: '/api/operations/reaper'
      fullPath: '/api/operations/reaper'
      preLoaderRoute: typeof ApiOperationsReaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$slug/': {
      id: '/v/$slug/'
      path: '/'
      fullPath: '/v/$slug/'
      preLoaderRoute: typeof VSlugIndexRouteImport
      parentRoute: typeof VSlugRoute
    }
    '/v/$slug/$documentId': {
      id: '/v/$slug/$documentId'
      path: '/$documentId'
      fullPath: '/v/$slug/$documentId'
      preLoaderRoute: typeof VSlugDocumentIdRouteImport
      parentRoute: typeof VSlugRoute
    }
    '/v/$slug/beacon': {
      id: '/v/$slug/beacon'
      path: '/beacon'
      fullPath: '/v/$slug/beacon'
      preLoaderRoute: typeof VSlugBeaconRouteImport
      parentRoute: typeof VSlugRoute
    }
    '/_authenticated/dashboard/analytics/': {
      id: '/_authenticated/dashboard/analytics/'
      path: '/analytics'
      fullPath: '/dashboard/analytics/'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/analytics/$linkId': {
      id: '/_authenticated/dashboard/analytics/$linkId'
      path: '/analytics/$linkId'
      fullPath: '/dashboard/analytics/$linkId'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsLinkIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/documents/': {
      id: '/_authenticated/dashboard/documents/'
      path: '/'
      fullPath: '/dashboard/documents/'
      preLoaderRoute: typeof AuthenticatedDashboardDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardDocumentsRouteRoute
    }
    '/_authenticated/dashboard/links/': {
      id: '/_authenticated/dashboard/links/'
      path: '/links'
      fullPath: '/dashboard/links/'
      preLoaderRoute: typeof AuthenticatedDashboardLinksIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/links/$linkId': {
      id: '/_authenticated/dashboard/links/$linkId'
      path: '/links/$linkId'
      fullPath: '/dashboard/links/$linkId'
      preLoaderRoute: typeof AuthenticatedDashboardLinksLinkIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/vaults/': {
      id: '/_authenticated/dashboard/vaults/'
      path: '/vaults'
      fullPath: '/dashboard/vaults/'
      preLoaderRoute: typeof AuthenticatedDashboardVaultsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/vaults/$vaultId': {
      id: '/_authenticated/dashboard/vaults/$vaultId'
      path: '/vaults/$vaultId'
      fullPath: '/dashboard/vaults/$vaultId'
      preLoaderRoute: typeof AuthenticatedDashboardVaultsVaultIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/demo/reports/$slug': {
      id: '/api/demo/reports/$slug'
      path: '/api/demo/reports/$slug'
      fullPath: '/api/demo/reports/$slug'
      preLoaderRoute: typeof ApiDemoReportsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/$documentId/bytes': {
      id: '/api/documents/$documentId/bytes'
      path: '/api/documents/$documentId/bytes'
      fullPath: '/api/documents/$documentId/bytes'
      preLoaderRoute: typeof ApiDocumentsDocumentIdBytesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$slug/bytes/$documentId': {
      id: '/v/$slug/bytes/$documentId'
      path: '/bytes/$documentId'
      fullPath: '/v/$slug/bytes/$documentId'
      preLoaderRoute: typeof VSlugBytesDocumentIdRouteImport
      parentRoute: typeof VSlugRoute
    }
    '/_authenticated/dashboard/documents/$documentId/': {
      id: '/_authenticated/dashboard/documents/$documentId/'
      path: '/$documentId'
      fullPath: '/dashboard/documents/$documentId/'
      preLoaderRoute: typeof AuthenticatedDashboardDocumentsDocumentIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardDocumentsRouteRoute
    }
    '/_authenticated/dashboard/documents/$documentId/edit': {
      id: '/_authenticated/dashboard/documents/$documentId/edit'
      path: '/$documentId/edit'
      fullPath: '/dashboard/documents/$documentId/edit'
      preLoaderRoute: typeof AuthenticatedDashboardDocumentsDocumentIdEditRouteImport
      parentRoute: typeof AuthenticatedDashboardDocumentsRouteRoute
    }
    '/api/operations/demo-environments/$environmentId/end': {
      id: '/api/operations/demo-environments/$environmentId/end'
      path: '/api/operations/demo-environments/$environmentId/end'
      fullPath: '/api/operations/demo-environments/$environmentId/end'
      preLoaderRoute: typeof ApiOperationsDemoEnvironmentsEnvironmentIdEndRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
  AuthAcceptInvitationInvitationIdRoute: typeof AuthAcceptInvitationInvitationIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
  AuthAcceptInvitationInvitationIdRoute: AuthAcceptInvitationInvitationIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedDashboardDocumentsRouteRouteChildren {
  AuthenticatedDashboardDocumentsIndexRoute: typeof AuthenticatedDashboardDocumentsIndexRoute
  AuthenticatedDashboardDocumentsDocumentIdEditRoute: typeof AuthenticatedDashboardDocumentsDocumentIdEditRoute
  AuthenticatedDashboardDocumentsDocumentIdIndexRoute: typeof AuthenticatedDashboardDocumentsDocumentIdIndexRoute
}

const AuthenticatedDashboardDocumentsRouteRouteChildren: AuthenticatedDashboardDocumentsRouteRouteChildren =
  {
    AuthenticatedDashboardDocumentsIndexRoute:
      AuthenticatedDashboardDocumentsIndexRoute,
    AuthenticatedDashboardDocumentsDocumentIdEditRoute:
      AuthenticatedDashboardDocumentsDocumentIdEditRoute,
    AuthenticatedDashboardDocumentsDocumentIdIndexRoute:
      AuthenticatedDashboardDocumentsDocumentIdIndexRoute,
  }

const AuthenticatedDashboardDocumentsRouteRouteWithChildren =
  AuthenticatedDashboardDocumentsRouteRoute._addFileChildren(
    AuthenticatedDashboardDocumentsRouteRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardDocumentsRouteRoute: typeof AuthenticatedDashboardDocumentsRouteRouteWithChildren
  AuthenticatedDashboardPeopleRoute: typeof AuthenticatedDashboardPeopleRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardAnalyticsLinkIdRoute: typeof AuthenticatedDashboardAnalyticsLinkIdRoute
  AuthenticatedDashboardLinksLinkIdRoute: typeof AuthenticatedDashboardLinksLinkIdRoute
  AuthenticatedDashboardVaultsVaultIdRoute: typeof AuthenticatedDashboardVaultsVaultIdRoute
  AuthenticatedDashboardAnalyticsIndexRoute: typeof AuthenticatedDashboardAnalyticsIndexRoute
  AuthenticatedDashboardLinksIndexRoute: typeof AuthenticatedDashboardLinksIndexRoute
  AuthenticatedDashboardVaultsIndexRoute: typeof AuthenticatedDashboardVaultsIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardDocumentsRouteRoute:
      AuthenticatedDashboardDocumentsRouteRouteWithChildren,
    AuthenticatedDashboardPeopleRoute: AuthenticatedDashboardPeopleRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardAnalyticsLinkIdRoute:
      AuthenticatedDashboardAnalyticsLinkIdRoute,
    AuthenticatedDashboardLinksLinkIdRoute:
      AuthenticatedDashboardLinksLinkIdRoute,
    AuthenticatedDashboardVaultsVaultIdRoute:
      AuthenticatedDashboardVaultsVaultIdRoute,
    AuthenticatedDashboardAnalyticsIndexRoute:
      AuthenticatedDashboardAnalyticsIndexRoute,
    AuthenticatedDashboardLinksIndexRoute:
      AuthenticatedDashboardLinksIndexRoute,
    AuthenticatedDashboardVaultsIndexRoute:
      AuthenticatedDashboardVaultsIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface OperationsRouteChildren {
  OperationsEnrollRoute: typeof OperationsEnrollRoute
}

const OperationsRouteChildren: OperationsRouteChildren = {
  OperationsEnrollRoute: OperationsEnrollRoute,
}

const OperationsRouteWithChildren = OperationsRoute._addFileChildren(
  OperationsRouteChildren,
)

interface VSlugRouteChildren {
  VSlugDocumentIdRoute: typeof VSlugDocumentIdRoute
  VSlugBeaconRoute: typeof VSlugBeaconRoute
  VSlugIndexRoute: typeof VSlugIndexRoute
  VSlugBytesDocumentIdRoute: typeof VSlugBytesDocumentIdRoute
}

const VSlugRouteChildren: VSlugRouteChildren = {
  VSlugDocumentIdRoute: VSlugDocumentIdRoute,
  VSlugBeaconRoute: VSlugBeaconRoute,
  VSlugIndexRoute: VSlugIndexRoute,
  VSlugBytesDocumentIdRoute: VSlugBytesDocumentIdRoute,
}

const VSlugRouteWithChildren = VSlugRoute._addFileChildren(VSlugRouteChildren)

interface VRouteChildren {
  VSlugRoute: typeof VSlugRouteWithChildren
}

const VRouteChildren: VRouteChildren = {
  VSlugRoute: VSlugRouteWithChildren,
}

const VRouteWithChildren = VRoute._addFileChildren(VRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  OperationsRoute: OperationsRouteWithChildren,
  VRoute: VRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDemoEndRoute: ApiDemoEndRoute,
  ApiDemoEntryRoute: ApiDemoEntryRoute,
  ApiOperationsDemoRecordsRoute: ApiOperationsDemoRecordsRoute,
  ApiOperationsPolicyRoute: ApiOperationsPolicyRoute,
  ApiOperationsReaperRoute: ApiOperationsReaperRoute,
  ApiDemoReportsSlugRoute: ApiDemoReportsSlugRoute,
  ApiDocumentsDocumentIdBytesRoute: ApiDocumentsDocumentIdBytesRoute,
  ApiOperationsDemoEnvironmentsEnvironmentIdEndRoute:
    ApiOperationsDemoEnvironmentsEnvironmentIdEndRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
